# This is a basic workflow to help you get started with Actions

name: CX-SCA Resolver

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Shell to download resolver and run scan based on repo.
        run: | 
          wget -O ScaResolver-linux64.tar.gz https://sca-downloads.s3.amazonaws.com/cli/1.2.3/ScaResolver-linux64.tar.gz
          mkdir ./resolver
          tar -xf ScaResolver-linux64.tar.gz --directory ./resolver
          ./resolver/ScaResolver -s ./ -e resolver -u ${{ secrets.CHECKMARX_SCA_USER }} -p ${{ secrets.CHECKMARX_SCA_PASSWORD }} -a ${{ secrets.CHECKMARX_SCA_ACCOUNT }} -n jr_${{ github.event.repository.name }} 
